### ISSUE TITLE
Pin D16 and D17 are swapped in Board variants.h

### ISSUE THREAD

**Issue by NikilXYZ** [sparkfun/SparkFun_Qwiic_Micro_SAMD21E#1]
### Subject of the issue
Pin D16 and D17 are swapped. 

### Your workbench
* Using board definition pack 1.7.5

### Steps to reproduce
Go to the variant.cpp file. The 16th entry corresponds to PA22 and 17th to PA23.
According to your [graphical datasheet](https://cdn.sparkfun.com/assets/learn_tutorials/9/1/7/Qwiic_Micro_Graphical_Datasheet.pdf) and your schematic, Pin D16 is PA23 and Pin D17 is PA22. 
One of the reviews for this board also noticed the error.

### Expected behaviour
If I `digitalWrite(16, HIGH)` it should turns on Pin 16. `digitalWrite(17, HIGH)` should turn on Pin 17. 

### Actual behaviour
Right now, if I `digitalWrite(16, HIGH)` it turns on Pin 17 and `digitalWrite(17, HIGH)` turns on Pin 16. 

### Steps to resolve
Go to the variant.cpp file, and flip the 16th entry and 17th entry in the pingroup array.
I did this locally and it works fine, but I cannot tell 100 high school students to go do this.

I can make a pull request if needed

**Comment by edspark** [comment]
Thanks for the pull request, it has been merged. As I mentioned in the pull request, I still have to update and do a new release of our Arduino Boards repository before you see it on the Arduino side.
